version: '3.8'

services:
  playnativa-web:
    build: .
    command: gunicorn playnativa_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
  